apiVersion: apps/v1
kind: Deployment
metadata: # metadata of deployment
  name: nginx-deployment
  labels:  # used by the service to match
    app: nginx
spec: # spec of deployment
  replicas: 3 # no of replicas of pod
  selector: # what is going to be inside the pod
    matchLabels:
      app: nginx  # used by the template to match
  template:
    metadata: # lables used by pod selector as given above
      labels: 
        app: nginx # should match with selector labels
    spec:
      containers:
        - name: nginx
          image: nginx # image of container
          ports:
            - containerPort: 80 # port where pod will forward request
