apiVersion: v1
kind: Service
metadata:
  name: k8-node-service
spec:
  selector:
    app: k8-node-deployment
  #type: LoadBalancer # if using external service with targetport
  type: NodePort # for ingress
  ports:
  - protocol: TCP
  #  name: http
    port: 3000  # for production, should be 80 if using external service otherwise same as app for ingress
    targetPort: 3000 # port running app on 

 

